// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ascscmomouomrtvubjkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzY3NjbW9tb3VvbXJ0dnViamtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzA4NjIsImV4cCI6MjA1OTc0Njg2Mn0.VKVIWYG4pasMIcodgXdOLo1zBksn4bQ7Rsvvlq3lsv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);